### ISSUE TITLE
Unable to install tensorflow-gpu==2.3.0rc0

### ISSUE THREAD

**Issue by AnzeVersnik** [theAIGuysCode/yolov4-deepsort#120]
I get this message while trying to execute conda env create -f conda-gpu.yml. I am able to run the code wieh a newer version of tensorflow-gpu but it will run at least 5 times slower than before I accidentally upgraded to the 2.7.0 version

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.3.0rc0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow-gpu==2.3.0rc0

failed

CondaEnvException: Pip failed

**Comment by jmudy** [comment]
It should work by installing Tensorflow 2.3.0:

`pip install tensorflow==2.3.0`
