### ISSUE TITLE
KeyError in generate_detections ImageEncoder function

### ISSUE THREAD

**Issue by AnzeVersnik** [theAIGuysCode/yolov4-deepsort#121]
![Untitled](https://user-images.githubusercontent.com/26359311/142081022-9a7443f5-5ddd-41a9-9550-e132cec51d40.png)

I get this issue and I am unable to solve it with the solutions provided on google

**Comment by Thanushan1997** [comment]
Hey I got the same error. How did you solve this. Can you mention that here
