### ISSUE TITLE
Detection works fine on CPU but generates random boxes (wrong or no detection) on GPU.

### ISSUE THREAD

**Issue by si-hafiz-abdullah** [theAIGuysCode/yolov4-deepsort#125]
I am using RTX 3070 GPU and CUDA version 10.1 with all specified requirements in the conda environment.
An image of results can be found here https://drive.google.com/file/d/1w4Js_2hKDZNICafz3ZY3S1bhYRIc-Yx0/view?usp=sharing

**Comment by tamnguyenbao2001** [comment]
I have a same problem, Have you fixed it?
