### ISSUE TITLE
Detection works fine on CPU but generates random boxes (wrong or no detection) on GPU

### ISSUE THREAD

**Issue by barkhaneum** [theAIGuysCode/yolov4-deepsort#127]
Hello, I'm testing in RTX 3080ti environment. Is there anyone who succeeded?

**Comment by supriamir** [comment]
same with me. how to solve it?

**Comment by kamal-nabhan** [comment]
What is the error that is being thrown?

**Comment by supriamir** [comment]
> What is the error that is being thrown?

the GPU works well but no bounding box detect to the object.

**Comment by barkhaneum** [comment]
I looked for various problems to solve the problem, and I think the CUDA version and Tensorflow version used in 3080ti are incompatible. As I lowered the Tensorflow version, I think it's a problem related to numpy. So I used the method of training on darknet with 3080TI and detecting with 2080super. To solve this problem, we need to fix the source again with the latest version of Tensorflow.

**Comment by DevAgarwal-588** [comment]
look at https://github.com/theAIGuysCode/yolov4-deepsort/pull/77 to solve the problem

**Comment by barkhaneum** [comment]
> look at #77 to solve the problem
Thank you it works perfectly for me :)
