### ISSUE TITLE
Why need to draw 2 rectangle?

### ISSUE THREAD

**Issue by ilu3000** [theAIGuysCode/yolov4-deepsort#19]
I don't understand with the code under "draw bbox on screen". Why do we need to draw two rectangle? What's the function on the second draw?

**Comment by pinczakko** [comment]
There are 2 rectangles for each detected object. The first one enclosed the detected object and the second one is used for the "caption" for the object (containing the object id number and its class)

**Comment by ilu3000** [comment]
Thank you so much for your reply
