### ISSUE TITLE
Resize image

### ISSUE THREAD

**Issue by Arhanel** [theAIGuysCode/yolov4-deepsort#2]
Hello, I have a problem with resizing images. Default size is 416 but when I try to set different size it gives me an error:
![image](https://user-images.githubusercontent.com/56166334/90745348-83c4a900-e2d0-11ea-8897-14b612822d8b.png)

YOLO accept ssizes that are N * 32, am I correct? So for example size 606 should work.

**Comment by pedromoraesh** [comment]
Did you find how to resize? I'm getting the same error.

**Comment by Arhanel** [comment]
Yes, for some reason I forgot about save_model.py. This is where you create weights etc and one of the parameters is input size for a new model.
