### ISSUE TITLE
Can this code run on jetson nano-2gb

### ISSUE THREAD

**Issue by xanthan011** [theAIGuysCode/yolov4-deepsort#49]
Well, its a straight up question..It's been days I've been trying to make this code work on nvivdia jetson-nano 2gb and due to some tensorflow issue..its not working..

So it would be helpful if anyone can straight up tell if that's the case

**Comment by xanthan011** [comment]
P.S. It works

**Comment by gururise** [comment]
> P.S. It works

Could you please provide some instructions/tips on how you got it to work on the Jetson Nano 2GB for those of us having this same issue?

**Comment by xanthan011** [comment]
Okay @gururise . I would like to help you out... Please comment if any specific error you are facing, if I know something about it, I will definitely help..
Also, while working with make sure you follow the official installation procedure for these libraries/modules:
python/python3
tensorflow (3 step procedure)
matplotlib
and u are good to go...rest of the libraries u can `pip install`  like u do normally..

**Comment by hongnam0167** [comment]
sr @xanthan011, i got a error sush as:
F tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc:493] Non-OK-status: GpuLaunchKernel(kernel, config.block_count, config.thread_per_block, 0, d.stream(), config.virtual_thread_count, images.data(), height_scale, width_scale, batch, in_height, in_width, channels, out_height, out_width, output.data()) status: Internal: too many resources requested for launch
Fatal Python error: Aborted

Did u get the same my error ? please let me know, tks u so muchhhh...

**Comment by lanzani** [comment]
Hi! 
How many fps did you get?

**Comment by lanzani** [comment]
> P.S. It works

Hi!
How many fps did you get?
