### ISSUE TITLE
cannot connect to X server 

### ISSUE THREAD

**Issue by 6Lackiu** [theAIGuysCode/yolov4-deepsort#59]
Hello, when I run "!python object_tracker.py --video ./data/video/cars.mp4 --output ./outputs/tracker.avi --model yolov4" on colab, it prompts "cannot connect to X server", what is the reason and how to solve it?
Looking forward to your reply, thank you!
![image](https://user-images.githubusercontent.com/52661423/112258728-f13f1a80-8ca1-11eb-8fb9-80e93721a45d.png)`

**Comment by jmudy** [comment]
Use the --dont_show flag:

`!python object_tracker.py --video ./data/video/cars.mp4 --output ./outputs/tracker.avi --model yolov4 --dont_show`

**Comment by 6Lackiu** [comment]
> Use the --dont_show flag:
> 
> `!python object_tracker.py --video ./data/video/cars.mp4 --output ./outputs/tracker.avi --model yolov4 --dont_show`

Thank you for your answer, but if I operate as you did, my output video is not tested and is the same as the original video. I don't know why.

**Comment by 6Lackiu** [comment]
> > 使用--dont_show标志：
> > `!python object_tracker.py --video ./data/video/cars.mp4 --output ./outputs/tracker.avi --model yolov4 --dont_show`
> 
> 感谢您的回答，但是如果我按您的方式操作，我的输出视频将未经测试，并且与原始视频相同。我不知道为什么

The problem is solved, thank you!

**Comment by rebeccamart** [comment]
Hi @6Lackiu , I have the same problem. I use the --dont_show flag, and my output video is the same as original. 
Have you been able to solve it? Thanks in advance.

**Comment by 6Lackiu** [comment]
> Hi @6Lackiu , I have the same problem. I use the --dont_show flag, and my output video is the same as original. Have you been able to solve it? Thanks in advance.

@rebeccamart I'd love to help you out, but unfortunately it's been a long time since I worked on this project and I can't remember the details. Maybe you can ask someone else. Feel sorry!
