### ISSUE TITLE
Video has ended or failed, try a different video format!

### ISSUE THREAD

**Issue by realtechspecs** [theAIGuysCode/yolov4-deepsort#70]
Each time I run the script, it shows a message at the end of the run cycle "Video has ended or failed, try a different video format!"

The output file has no object recognition boxes on it, it's just a clone of the input video.

Has anyone else encountered the issue? Any clues how to go about solving this problem?

I'm running it on a venv as specified in the readme

**Comment by realtechspecs** [comment]
I managed to get it to work by changing the input file from .mp4 to .avi format. Apparently, the script only works with avi video files.

**Comment by RonaldYuren** [comment]
> I managed to get it to work by changing the input file from .mp4 to .avi format. Apparently, the script only works with avi video files.

Does the video has limit?   I tried to transfer video into " .avi " but it didn't work
