### ISSUE TITLE
yolov4-tiny not working in test.mp4

### ISSUE THREAD

**Issue by alanotmt** [theAIGuysCode/yolov4-deepsort#94]
I following the readme.md step to run all the file and no any error. 
when I using yolov4 model and run object_tracker.py it is work.
but yolov4-tiny model got nothing bbox.

**Comment by liuyang77712** [comment]
do you resolve it?

**Comment by farshokat** [comment]
yes, I using yolov4-tiny and model cannot anything object. Do you solve it? can you share with me?
